# Config  ================================================
stages:
  - security
  - build
  - test
  - check-env
  - deploy-test
  - deploy-prod

variables:
  REGISTRY_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH-$CI_COMMIT_SHA
  DOCKER_VERSION: "29.0.4"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        VERSION_TAG: "latest"
    - if: $CI_COMMIT_BRANCH == "test_kube"
      variables:
        VERSION_TAG: "test"
    - if: $CI_COMMIT_BRANCH == "test_server"
    - when: always

# Gitleaks ================================================
gitleaks:
  stage: security
  image:
    name: zricethezav/gitleaks:latest
    entrypoint: [""]
  tags:
    - runner-build
  rules:
    - when: always
  script:
      - |
        if [ -n "$CI_MERGE_REQUEST_TARGET_BRANCH_SHA" ]; then
          LOG_OPTS="${CI_MERGE_REQUEST_TARGET_BRANCH_SHA}..${CI_COMMIT_SHA}"
        elif [ "$CI_COMMIT_BEFORE_SHA" = "0000000000000000000000000000000000000000" ] || [ -z "$CI_COMMIT_BEFORE_SHA" ]; then
          LOG_OPTS="-n 10 ${CI_COMMIT_SHA}"
        else
          LOG_OPTS="${CI_COMMIT_BEFORE_SHA}..${CI_COMMIT_SHA}"
        fi
      - gitleaks protect --verbose --log-opts="${LOG_OPTS}" --report-format=sarif --report-path=gitleaks-sast-report.json
  artifacts:
    reports:
      sast: gitleaks-sast-report.json
    expire_in: 1 week
    when: always

# Build & Push ================================================
build_push_job:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
    - if: $CI_COMMIT_BRANCH == "test_kube"
  image: docker:$DOCKER_VERSION
  tags:
    - runner-build
  parallel:
    matrix:
      - APP: ["airflow", "api-prod", "api-predict"]
        DOCKERFILE: ["Dockerfile"]
      - APP: ["airflow", "api-predict"]
        DOCKERFILE: ["Dockerfile.lts"]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
      - |
        if [ "$DOCKERFILE" = "Dockerfile.lts" ]; then
          TAG_SUFFIX="-lts"
        else
          TAG_SUFFIX=""
        fi
      - IMAGE_NAME="$CI_REGISTRY_IMAGE/$APP"
      - FULL_SHA_TAG="$IMAGE_NAME:$VERSION_TAG$TAG_SUFFIX-$CI_COMMIT_SHORT_SHA"
      - LATEST_TAG="$IMAGE_NAME:$VERSION_TAG$TAG_SUFFIX"

      - docker build --cache-from $LATEST_TAG -t $FULL_SHA_TAG -t $LATEST_TAG -f $APP/$DOCKERFILE .

      - docker push $FULL_SHA_TAG
      - docker push $LATEST_TAG

# Test  ================================================
test-docker-image:
  stage: test
  needs:
    - job: build_push_job
  tags:
    - runner-build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "test_kube"
  parallel:
    matrix:
      - APP: ["airflow", "api-prod", "api-predict"]
        TAG_SUFFIX: [""]
      - APP: ["airflow", "api-predict"]
        TAG_SUFFIX: ["-lts"]
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - IMAGE="$CI_REGISTRY_IMAGE/$APP:$VERSION_TAG$TAG_SUFFIX-$CI_COMMIT_SHORT_SHA"
    - docker pull $IMAGE
    - |
      if [ "$APP" = "airflow" ]; then
        CHECK="from airflow import DAG; print('OK')"
      else
        CHECK="from main import app; print('OK')"
      fi
    - docker run --rm $IMAGE python -c "$CHECK"

# Check env  ================================================
check-processor-test:
  stage: check-env
  rules:
    - if: $CI_COMMIT_BRANCH == "test_kube"
  tags:
    - runner-test-kube
  environment:
      name: serveur-test-kube
  script:
    - !reference [.script-check-processor, script]
  artifacts:
    reports:
      dotenv: build.env

check-processor-prod:
  stage: check-env
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  tags:
    - runner-prod
  environment:
      name: serveur-prod
  script:
    - !reference [.script-check-processor, script]
  artifacts:
    reports:
      dotenv: build.env

.script-check-processor:
  script:
  - export KUBECONFIG="$KUBECONFIG_CONTENT"
  - RUST_NODES=$(kubectl get nodes -l rustcompatible=true -o name)
  - |
    if [ -z "$RUST_NODES" ]; then
      echo "ENV_TAG=-lts" >> build.env
    else
      echo "ENV_TAG=" >> build.env
    fi
  - echo "VERSION_TAG=$VERSION_TAG" >> build.env

# Deploy  ================================================
deploy_to_test-kube:
  stage: deploy-test
  needs:
    - job: build_push_job
    - job: check-processor-test
      artifacts: true
  dependencies:
    - check-processor-test
  tags:
    - runner-test-kube
  environment:
      name: serveur-test-kube
  rules:
    - if: $CI_COMMIT_BRANCH == "test_kube"
  script:
  - !reference [.init-deploy-kube, script]

deploy_to_prod:
  stage: deploy-prod
  needs:
    - job: build_push_job
    - job: check-processor-prod
      artifacts: true
  dependencies:
    - check-processor-prod
  tags:
    - runner-prod
  environment:
      name: serveur-prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - !reference [.init-deploy-kube, script]

.init-deploy-kube:
  script:
  - export KUBECONFIG="$KUBECONFIG_CONTENT"

  - if [ -f build.env ]; then export $(xargs < build.env); fi

  - |
    helm upgrade --install apis ./k3s/apis \
      --namespace flight-project \
      --create-namespace \
      -f k3s/apis/values.yaml \
      --set persistence.nodeName=$K3S_NODE_NAME \
      --set persistence.hostPath=$K3S_HOST_PATH \
      --set image.tag=$VERSION_TAG \
      --set apiPredict.envTag=$ENV_TAG

  - helm repo add apache-airflow https://airflow.apache.org
  - helm repo update

  # Apply material restrictions for tests if branch is "test_kube"
  - |
    HELM_CMD="helm upgrade --install airflow apache-airflow/airflow \
      --version 1.21.0 \
      --namespace flight-project \
      -f k3s/airflow/values.yaml"

    if [ "$CI_COMMIT_BRANCH" = "test_kube" ]; then
      HELM_CMD="$HELM_CMD -f k3s/airflow/values-test.yaml"
    fi

    HELM_CMD="$HELM_CMD --set images.airflow.tag=$VERSION_TAG$ENV_TAG"
    $HELM_CMD

  # Monitoring
  - cp monitoring/grafana/provisioning/dashboards/fastapi.json k3s/monitoring/dashboards/fastapi.json
  - cp monitoring/grafana/provisioning/dashboards/airflow.json k3s/monitoring/dashboards/airflow.json

  - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  - helm repo update

  - |
    helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
      --namespace monitoring \
      --create-namespace \
      -f k3s/monitoring/values.yaml \
      --set grafana.adminPassword=$GF_PASSWORD

  - |
    kubectl create configmap grafana-dashboards \
      --from-file=fastapi.json=k3s/monitoring/dashboards/fastapi.json \
      --from-file=airflow.json=k3s/monitoring/dashboards/airflow.json \
      --namespace monitoring \
      --dry-run=client -o yaml | kubectl apply -f -

# deploy_to_test:
#   stage: deploy-test
#   tags:
#     - runner-test
#   environment:
#       name: serveur-test
#   rules:
#     - if: $CI_COMMIT_BRANCH == "test_server"
#   script:
#     - cp $ENV_FILE .env
#     - echo "Lufth_client_secret=$Lufth_client_secret" >> .env
#     - echo "Lufth_client_id=$Lufth_client_id" >> .env
#     - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
#     - echo "AIRFLOW_PASSWORD=$AIRFLOW_PASSWORD" >> .env
#     - echo "AIRFLOW_LOGS_PATH=$AIRFLOW_LOGS_PATH" >> .env
#     - echo "AIRFLOW_API_SECRET=$AIRFLOW_API_SECRET" >> .env
#     - echo "EXTRACTED_PATH=$EXTRACTED_PATH" >> .env
#     - echo "PENDING_PATH=$PENDING_PATH" >> .env
#     - echo "ARCHIVES_PATH=$ARCHIVES_PATH" >> .env
#     - echo "MODEL_PATH=$MODEL_PATH" >> .env
#     - docker compose down --remove-orphans
#     - docker compose up -d --build
