# Config  ================================================
stages:
  - build
  - test
  - push-images
  - check-env
  - deploy-test
  - deploy-prod

variables:
  REGISTRY_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH-$CI_COMMIT_SHA
  DOCKER_VERSION: "29.0.4"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        VERSION_TAG: "latest"
    - if: $CI_COMMIT_BRANCH == "test_kube"
      variables:
        VERSION_TAG: "test"
    - if: $CI_COMMIT_BRANCH == "test_server"
    - when: always


# Build  ================================================
build_job:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "test_kube"
  image: docker:$DOCKER_VERSION
  tags:
    - runner-build
  script:
  #Build Airflow
  - docker build -t $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-$CI_COMMIT_SHORT_SHA -f airflow/Dockerfile .
  - docker build -t $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-lts-$CI_COMMIT_SHORT_SHA -f airflow/Dockerfile.lts .
  - docker tag $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG
  - docker tag $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-lts-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-lts

  #Build Api-prod
  - docker build -t $CI_REGISTRY_IMAGE/api-prod:$VERSION_TAG-$CI_COMMIT_SHORT_SHA -f api-prod/Dockerfile .
  - docker tag $CI_REGISTRY_IMAGE/api-prod:$VERSION_TAG-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/api-prod:$VERSION_TAG

  #Build Api-predict
  - docker build -t $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-$CI_COMMIT_SHORT_SHA -f api-predict/Dockerfile .
  - docker build -t $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-lts-$CI_COMMIT_SHORT_SHA -f api-predict/Dockerfile.lts .
  - docker tag $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG
  - docker tag $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-lts-$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-lts

# Test  ================================================
test-docker-image :
  stage: test
  tags:
    - runner-build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "test_kube"
  script:
  #Test Airflow
  - docker run --rm $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-$CI_COMMIT_SHORT_SHA python -c "from main import app; print('OK')"
  - docker run --rm $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-lts-$CI_COMMIT_SHORT_SHA python -c "from main import app; print('OK')"

  #Test Api-prod
  - docker run --rm $CI_REGISTRY_IMAGE/api-prod:$VERSION_TAG-$CI_COMMIT_SHORT_SHA airflow dags list

  #Test Api-predict
  - docker run --rm $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-$CI_COMMIT_SHORT_SHA python -c "from main import app; print('OK')"
  - docker run --rm $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-lts-$CI_COMMIT_SHORT_SHA python -c "from main import app; print('OK')"

# Push  ================================================
push-image :
  stage: push-images
  tags:
    - runner-build
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "test_kube"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
  #Push Airflow
  - docker push $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-$CI_COMMIT_SHORT_SHA
  - docker push $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-lts-$CI_COMMIT_SHORT_SHA
  - docker push $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG
  - docker push $CI_REGISTRY_IMAGE/airflow:$VERSION_TAG-lts

  #Push Api-prod
  - docker push $CI_REGISTRY_IMAGE/api-prod:$VERSION_TAG-$CI_COMMIT_SHORT_SHA
  - docker push $CI_REGISTRY_IMAGE/api-prod:$VERSION_TAG

  #Push Api-predict
  - docker push $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-$CI_COMMIT_SHORT_SHA
  - docker push $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-lts-$CI_COMMIT_SHORT_SHA
  - docker push $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG
  - docker push $CI_REGISTRY_IMAGE/api-predict:$VERSION_TAG-lts

# Check env  ================================================
check-processor-test:
  stage: check-env
  rules:
    - if: $CI_COMMIT_BRANCH == "test_kube"
  tags:
    - runner-test-kube
  script:
    - !reference [.script-check-processor, script]
  artifacts:
    reports:
      dotenv: build.env

check-processor-prod:
  stage: check-env
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
  tags:
    - runner-prod
  script:
    - !reference [.script-check-processor, script]
  artifacts:
    reports:
      dotenv: build.env

.script-check-processor:
  script:
  - export KUBECONFIG="$KUBECONFIG_CONTENT"
  - RUST_NODES=$(kubectl get nodes -l rustcompatible=true -o name)
  - |
    if [ -z "$RUST_NODES" ]; then
      echo "ENV_TAG=" >> build.env
    else
      echo "ENV_TAG=-lts" >> build.env
    fi
  - echo "VERSION_TAG=$VERSION_TAG" >> build.env

# Deploy  ================================================
deploy_to_test-kube:
  stage: deploy-test
  needs:
    - job: build_job
    - job: check-processor-test
    - job: push-image
      artifacts: true
  dependencies:
    - check-processor-test
  tags:
    - runner-test-kube
  environment:
      name: serveur-test-kube
  rules:
    - if: $CI_COMMIT_BRANCH == "test_kube"
  script:
  - !reference [.init-deploy-kube, script]

deploy_to_prod:
  stage: deploy-prod
  needs:
    - job: build_job
    - job: check-processor-prod
    - job: push-image
      artifacts: true
  dependencies:
    - check-processor-prod
  tags:
    - runner-prod
  environment:
      name: serveur-prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - !reference [.init-deploy-kube, script]

.init-deploy-kube:
  script:
  - export KUBECONFIG="$KUBECONFIG_CONTENT"
  
  - if [ -f build.env ]; then export $(xargs < build.env); fi

  - helm upgrade --install apis ./k3s/apis \
    -f k3s/apis/values.yaml \
    --set persistence.nodeName=$K3S_NODE_NAME \
    --set persistence.hostPath=$K3S_HOST_PATH \
    --set image.tag=$VERSION_TAG \
    --set apiPredict.envTag=$ENV_TAG

  - helm repo add apache-airflow https://airflow.apache.org
  - helm repo update

  # Apply material restrictions for tests if branch is "test_kube"
  - HELM_CMD="helm upgrade --install airflow apache-airflow/airflow \
    --version 1.21.0 \
    --namespace flight-project \
    --create-namespace \
    -f k3s/airflow/values.yaml"
  - |
    if [ "$CI_COMMIT_BRANCH" = "test_kube" ]; then
      HELM_CMD="$HELM_CMD -f k3s/airflow/values-test.yaml"
    fi
  - HELM_CMD="$HELM_CMD --set images.airflow.tag=$VERSION_TAG$ENV_TAG"
  - $HELM_CMD


# deploy_to_test:
#   stage: deploy-test
#   tags:
#     - runner-test
#   environment:
#       name: serveur-test
#   rules:
#     - if: $CI_COMMIT_BRANCH == "test_server"
#   script:
#     - cp $ENV_FILE .env
#     - echo "Lufth_client_secret=$Lufth_client_secret" >> .env
#     - echo "Lufth_client_id=$Lufth_client_id" >> .env
#     - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
#     - echo "AIRFLOW_PASSWORD=$AIRFLOW_PASSWORD" >> .env
#     - echo "AIRFLOW_LOGS_PATH=$AIRFLOW_LOGS_PATH" >> .env
#     - echo "AIRFLOW_API_SECRET=$AIRFLOW_API_SECRET" >> .env
#     - echo "EXTRACTED_PATH=$EXTRACTED_PATH" >> .env
#     - echo "PENDING_PATH=$PENDING_PATH" >> .env
#     - echo "ARCHIVES_PATH=$ARCHIVES_PATH" >> .env
#     - echo "MODEL_PATH=$MODEL_PATH" >> .env
#     - docker compose down --remove-orphans
#     - docker compose up -d --build