apiVersion: v1
kind: Service
metadata:
  name: api-predict
  namespace: flight-project
spec:
  selector:
    app: api-predict
  ports:
    - protocol: TCP
      nodePort: 32001
      targetPort: 8001
      port: 8001
  type: LoadBalancer