# Airflow 3 Architecture ================================================
apiServer:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "512Mi"

scheduler:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "512Mi"

worker:
  replicas: 1
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "512Mi"

postgresql:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"