# Airflow 3 Architecture ================================================
redis:
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"

postgresql:
  resources:
    limits:
      cpu: "100m"
      memory: "200Mi"
    requests:
      cpu: "50m"
      memory: "100Mi"

apiServer:
  replicas: 1
  livenessProbe:
    periodSeconds: 30
    timeoutSeconds: 20
    failureThreshold: 3
  startupProbe:
    failureThreshold: 12
    timeoutSeconds: 30
  resources:
    limits:
      cpu: "200m"
      memory: "1Gi"
    requests:
      cpu: "50m"
      memory: "128Mi"

scheduler:
  replicas: 1
  startupProbe:
    failureThreshold: 12
    timeoutSeconds: 30
  resources:
    limits:
      cpu: "200m"
      memory: "1Gi"
    requests:
      cpu: "50m"
      memory: "128Mi"

dagProcessor:
  replicas: 1
  resources:
    limits:
      cpu: "200m"
      memory: "1Gi"
    requests:
      cpu: "50m"
      memory: "256Mi"

worker:
  replicas: 1
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "50m"
      memory: "150Mi"