apiVersion: apps/v2
kind: Deployment
metadata:
  name: {{ .Values.apiProd.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.apiProd.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apiProd.name }}
      version: {{ .Values.image.tag }}
  template:
    metadata:
      labels:
        app: {{ .Values.apiProd.name }}
        version: {{ .Values.image.tag }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
      - name: {{ .Values.apiProd.name }}
        image: {{ .Values.image.registry }}/api-prod:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: AIRFLOW_API_URL
          value: "http://airflow-api-server:8080"
        - name: EXTRACTED_PATH
          value: /app/extracted
        - name: PENDING_PATH
          value: /app/pending
        - name: ARCHIVES_PATH
          value: /app/archives
        - name: MODEL_PATH
          value: /app/output_model
        envFrom:
        - secretRef:
            name: {{ .Values.credentialsSecret }}
        volumeMounts:
        - name: common-data
          mountPath: /app/extracted
          subPath: Weekly
        - name: common-data
          mountPath: /app/pending
          subPath: Pending
        - name: common-data
          mountPath: /app/archives
          subPath: Archives
        - name: common-data
          mountPath: /app/output_model
          subPath: Model
      volumes:
        - name: common-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.pvcName }}