apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}